<?php
/**
 * @var \Magento\Theme\Block\Html\Header $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<div class="container-footer-blocks">
    <div class="footer-link-block company">
        <?= $block->getChildHtml('footer-company') ?>
    </div>
    <div class="footer-link-block support">
        <?= $block->getChildHtml('footer-support') ?>
    </div>
    <div class="footer-link-block legal">
        <?= $block->getChildHtml('footer-legal') ?>
    </div>
    <div class="footer-link-block install-app">
        <?= $block->getChildHtml('footer-install-app') ?>
    </div>
</div>


